---
title: "GMV_plots_mplus"
author: "Alexis Brieant"
date: '2025-08-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##Starting with Version 8.9, plots can be viewed in R with the R Shiny app, Mplus Plots User Interface. Mplus Plots User Interface app accepts the Mplus GH5 file as input and provides a list of available plots. While Mac and Linux users cannot get Mplus plots in the current Mplus version using the PLOT command, they can use the PLOT command to generate a GH5 file for use in the Mplus Plots User Interface app. The app uses the Mplus R functions to display selected plots.
```


```{r load shiny app}

install.packages('shiny')
install.packages('DT')
install.packages('data.table')

loadedNamespaces()
if ("fastmap" %in% loadedNamespaces()) {
  unloadNamespace("fastmap")
}

install.packages("fastmap")
packageVersion("fastmap")

library(fastmap)
library(shiny)
library(DT)
library(data.table)

shiny::runApp('/Users/ab3377/Library/CloudStorage/OneDrive-UniversityofVermont/OneDrive/Manuscripts/reg report DCN/pubertybrain/GMV_timing_tempo_models/MplusPlotsUI')

```
